version: '3'
services:
  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - "8080:8080"
    environment:
      - VITE_IP_ADDR=0.0.0.0
      - VITE_PORT=8080
      - VITE_LOGS_DIR=logs/
      - VITE_DB_HOST=127.0.0.1
      - VITE_DB_PORT=5432
      - VITE_DB_USER=asterviz
      - VITE_DB_PASS=asterviz
      - VITE_DB_NAME=asterviz
      - VITE_CSMS_IP=localhost
      - VITE_CSMS_PORT=5203
      - VITE_AUTH0_DOMAIN="dev-msr1bjuppruzjysb.us.auth0.com"
      - VITE_AUTH0_CLIENT_ID="iHXlMOKYE0OF9MkTn4tpYelW5vXWwZ4t"
      - VITE_AUTH0_CLIENT_SECRET="RSQF9oM4zFVLIE30dmpMOk7judz0sA2kjDJgO_0ey47vFcdHd5wBOC7RaHNJutVb"
      - VITE_AUTH0_AUDIENCE="https://dev-msr1bjuppruzjysb.us.auth0.com/api/v2/"
      - VITE_AUTH0_MANAGE_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InctYlNwdElzY1l0UF9oY2h1cXprVCJ9.eyJpc3MiOiJodHRwczovL2Rldi1tc3IxYmp1cHBydXpqeXNiLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJYMDlnRUtZYmhVakVjUWlGMW5NZEZ4cUpJZ0JPckR6VUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9kZXYtbXNyMWJqdXBwcnV6anlzYi51cy5hdXRoMC5jb20vYXBpL3YyLyIsImlhdCI6MTY3OTM1MzA3NywiZXhwIjoxNjc5OTU3ODc3LCJhenAiOiJYMDlnRUtZYmhVakVjUWlGMW5NZEZ4cUpJZ0JPckR6VSIsInNjb3BlIjoicmVhZDpjbGllbnRfZ3JhbnRzIGNyZWF0ZTpjbGllbnRfZ3JhbnRzIGRlbGV0ZTpjbGllbnRfZ3JhbnRzIHVwZGF0ZTpjbGllbnRfZ3JhbnRzIHJlYWQ6dXNlcnMgdXBkYXRlOnVzZXJzIGRlbGV0ZTp1c2VycyBjcmVhdGU6dXNlcnMgcmVhZDp1c2Vyc19hcHBfbWV0YWRhdGEgdXBkYXRlOnVzZXJzX2FwcF9tZXRhZGF0YSBkZWxldGU6dXNlcnNfYXBwX21ldGFkYXRhIGNyZWF0ZTp1c2Vyc19hcHBfbWV0YWRhdGEgcmVhZDp1c2VyX2N1c3RvbV9ibG9ja3MgY3JlYXRlOnVzZXJfY3VzdG9tX2Jsb2NrcyBkZWxldGU6dXNlcl9jdXN0b21fYmxvY2tzIGNyZWF0ZTp1c2VyX3RpY2tldHMgcmVhZDpjbGllbnRzIHVwZGF0ZTpjbGllbnRzIGRlbGV0ZTpjbGllbnRzIGNyZWF0ZTpjbGllbnRzIHJlYWQ6Y2xpZW50X2tleXMgdXBkYXRlOmNsaWVudF9rZXlzIGRlbGV0ZTpjbGllbnRfa2V5cyBjcmVhdGU6Y2xpZW50X2tleXMgcmVhZDpjb25uZWN0aW9ucyB1cGRhdGU6Y29ubmVjdGlvbnMgZGVsZXRlOmNvbm5lY3Rpb25zIGNyZWF0ZTpjb25uZWN0aW9ucyByZWFkOnJlc291cmNlX3NlcnZlcnMgdXBkYXRlOnJlc291cmNlX3NlcnZlcnMgZGVsZXRlOnJlc291cmNlX3NlcnZlcnMgY3JlYXRlOnJlc291cmNlX3NlcnZlcnMgcmVhZDpkZXZpY2VfY3JlZGVudGlhbHMgdXBkYXRlOmRldmljZV9jcmVkZW50aWFscyBkZWxldGU6ZGV2aWNlX2NyZWRlbnRpYWxzIGNyZWF0ZTpkZXZpY2VfY3JlZGVudGlhbHMgcmVhZDpydWxlcyB1cGRhdGU6cnVsZXMgZGVsZXRlOnJ1bGVzIGNyZWF0ZTpydWxlcyByZWFkOnJ1bGVzX2NvbmZpZ3MgdXBkYXRlOnJ1bGVzX2NvbmZpZ3MgZGVsZXRlOnJ1bGVzX2NvbmZpZ3MgcmVhZDpob29rcyB1cGRhdGU6aG9va3MgZGVsZXRlOmhvb2tzIGNyZWF0ZTpob29rcyByZWFkOmFjdGlvbnMgdXBkYXRlOmFjdGlvbnMgZGVsZXRlOmFjdGlvbnMgY3JlYXRlOmFjdGlvbnMgcmVhZDplbWFpbF9wcm92aWRlciB1cGRhdGU6ZW1haWxfcHJvdmlkZXIgZGVsZXRlOmVtYWlsX3Byb3ZpZGVyIGNyZWF0ZTplbWFpbF9wcm92aWRlciBibGFja2xpc3Q6dG9rZW5zIHJlYWQ6c3RhdHMgcmVhZDppbnNpZ2h0cyByZWFkOnRlbmFudF9zZXR0aW5ncyB1cGRhdGU6dGVuYW50X3NldHRpbmdzIHJlYWQ6bG9ncyByZWFkOmxvZ3NfdXNlcnMgcmVhZDpzaGllbGRzIGNyZWF0ZTpzaGllbGRzIHVwZGF0ZTpzaGllbGRzIGRlbGV0ZTpzaGllbGRzIHJlYWQ6YW5vbWFseV9ibG9ja3MgZGVsZXRlOmFub21hbHlfYmxvY2tzIHVwZGF0ZTp0cmlnZ2VycyByZWFkOnRyaWdnZXJzIHJlYWQ6Z3JhbnRzIGRlbGV0ZTpncmFudHMgcmVhZDpndWFyZGlhbl9mYWN0b3JzIHVwZGF0ZTpndWFyZGlhbl9mYWN0b3JzIHJlYWQ6Z3VhcmRpYW5fZW5yb2xsbWVudHMgZGVsZXRlOmd1YXJkaWFuX2Vucm9sbG1lbnRzIGNyZWF0ZTpndWFyZGlhbl9lbnJvbGxtZW50X3RpY2tldHMgcmVhZDp1c2VyX2lkcF90b2tlbnMgY3JlYXRlOnBhc3N3b3Jkc19jaGVja2luZ19qb2IgZGVsZXRlOnBhc3N3b3Jkc19jaGVja2luZ19qb2IgcmVhZDpjdXN0b21fZG9tYWlucyBkZWxldGU6Y3VzdG9tX2RvbWFpbnMgY3JlYXRlOmN1c3RvbV9kb21haW5zIHVwZGF0ZTpjdXN0b21fZG9tYWlucyByZWFkOmVtYWlsX3RlbXBsYXRlcyBjcmVhdGU6ZW1haWxfdGVtcGxhdGVzIHVwZGF0ZTplbWFpbF90ZW1wbGF0ZXMgcmVhZDptZmFfcG9saWNpZXMgdXBkYXRlOm1mYV9wb2xpY2llcyByZWFkOnJvbGVzIGNyZWF0ZTpyb2xlcyBkZWxldGU6cm9sZXMgdXBkYXRlOnJvbGVzIHJlYWQ6cHJvbXB0cyB1cGRhdGU6cHJvbXB0cyByZWFkOmJyYW5kaW5nIHVwZGF0ZTpicmFuZGluZyBkZWxldGU6YnJhbmRpbmcgcmVhZDpsb2dfc3RyZWFtcyBjcmVhdGU6bG9nX3N0cmVhbXMgZGVsZXRlOmxvZ19zdHJlYW1zIHVwZGF0ZTpsb2dfc3RyZWFtcyBjcmVhdGU6c2lnbmluZ19rZXlzIHJlYWQ6c2lnbmluZ19rZXlzIHVwZGF0ZTpzaWduaW5nX2tleXMgcmVhZDpsaW1pdHMgdXBkYXRlOmxpbWl0cyBjcmVhdGU6cm9sZV9tZW1iZXJzIHJlYWQ6cm9sZV9tZW1iZXJzIGRlbGV0ZTpyb2xlX21lbWJlcnMgcmVhZDplbnRpdGxlbWVudHMgcmVhZDphdHRhY2tfcHJvdGVjdGlvbiB1cGRhdGU6YXR0YWNrX3Byb3RlY3Rpb24gcmVhZDpvcmdhbml6YXRpb25zIHVwZGF0ZTpvcmdhbml6YXRpb25zIGNyZWF0ZTpvcmdhbml6YXRpb25zIGRlbGV0ZTpvcmdhbml6YXRpb25zIGNyZWF0ZTpvcmdhbml6YXRpb25fbWVtYmVycyByZWFkOm9yZ2FuaXphdGlvbl9tZW1iZXJzIGRlbGV0ZTpvcmdhbml6YXRpb25fbWVtYmVycyBjcmVhdGU6b3JnYW5pemF0aW9uX2Nvbm5lY3Rpb25zIHJlYWQ6b3JnYW5pemF0aW9uX2Nvbm5lY3Rpb25zIHVwZGF0ZTpvcmdhbml6YXRpb25fY29ubmVjdGlvbnMgZGVsZXRlOm9yZ2FuaXphdGlvbl9jb25uZWN0aW9ucyBjcmVhdGU6b3JnYW5pemF0aW9uX21lbWJlcl9yb2xlcyByZWFkOm9yZ2FuaXphdGlvbl9tZW1iZXJfcm9sZXMgZGVsZXRlOm9yZ2FuaXphdGlvbl9tZW1iZXJfcm9sZXMgY3JlYXRlOm9yZ2FuaXphdGlvbl9pbnZpdGF0aW9ucyByZWFkOm9yZ2FuaXphdGlvbl9pbnZpdGF0aW9ucyBkZWxldGU6b3JnYW5pemF0aW9uX2ludml0YXRpb25zIHJlYWQ6b3JnYW5pemF0aW9uc19zdW1tYXJ5IGNyZWF0ZTphY3Rpb25zX2xvZ19zZXNzaW9ucyBjcmVhdGU6YXV0aGVudGljYXRpb25fbWV0aG9kcyByZWFkOmF1dGhlbnRpY2F0aW9uX21ldGhvZHMgdXBkYXRlOmF1dGhlbnRpY2F0aW9uX21ldGhvZHMgZGVsZXRlOmF1dGhlbnRpY2F0aW9uX21ldGhvZHMiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.Gn2TB9KVSOp-e3csUdpCnFAJNDiw95HGUpTP01IHw6Q9wnBr-YBdbt2a0sZGFBA53ZsBOAEefsDRWuEKmVzlyZPCQNoQopVe9o-037RiRaR6px0qsaqEZ_NGd7zVdEHDUWUNImy_heFGQ6kEorEWA8ZN2bHIjaVJz331vRH-0PEPLWfpwoGcI9HXWn1iX0vPrcEh7ytOHgzdfP_bpH-jiWtpfdqcsXjt1jRNtLJuipT0kmNraVuQM6GmRCG5HgvXYbK5AyU0H2ykeAJrwpDHfK8Ln1Hoj-dVgitoX0kNw5-7c3-HfqvUoAzXfMp4gD5qDTfL_VcMeYkZkbSSq2_iAQ"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432" 
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=asterviz
      - POSTGRES_PASSWORD=asterviz
      - POSTGRES_DB=asterviz

  minio:
    container_name: minio
    image: docker.io/bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_DEFAULT_BUCKETS=asterviz:public
      - MINIO_ROOT_USER=minioUser
      - MINIO_ROOT_PASSWORD=minioPass
      - MINIO_SERVER_ACCESS_KEY=minioUser
      - MINIO_SERVER_SECRET_KEY=minioPass
    volumes:
      - minio_data:/data

  frontend:
    container_name: frontend
    build: ./frontend/
    restart: always
    ports:
      - "88:80" # We need to map here for convenience, so we don't conflict with a potential possible local server
    environment:
      - VITE_BACKEND_IP=localhost
      - VITE_BACKEND_PORT=8080
      - VITE_MINIO_IP=localhost
      - VITE_MINIO_PORT=9000
      - VITE_CSMS_IP=localhost
      - VITE_CSMS_PORT=5203
      - VITE_AUTH0_DOMAIN="dev-msr1bjuppruzjysb.us.auth0.com"
      - VITE_AUTH0_CLIENT_ID="iHXlMOKYE0OF9MkTn4tpYelW5vXWwZ4t"
      - VITE_AUTH0_CLIENT_SECRET="RSQF9oM4zFVLIE30dmpMOk7judz0sA2kjDJgO_0ey47vFcdHd5wBOC7RaHNJutVb"
      - VITE_AUTH0_AUDIENCE="https://dev-msr1bjuppruzjysb.us.auth0.com/api/v2/"

  routecs:
    container_name: routecs
    build: ./routeCS/MyRoute
    restart: always
    ports:
      - "5203:5203"
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=asterviz
      - DB_PASS=asterviz
      - DB_NAME=asterviz
      - SERVER_IP=localhost
      - SERVER_PORT=8080
    depends_on: #This is a lie
      - postgres

volumes:
  minio_data:
    driver: local
  db:
    driver: local